version: '3'
services:
        web:
                image: jncs_db_layer
                build: .
                ports:
                        - "8679:8679"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped